# Generated by Django 4.0.4 on 2022-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_release'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='release',
            name='date',
            field=models.DateField(verbose_name='release date'),
        ),
    ]
